# Generated by Django 4.1.9 on 2023-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=2)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
